name: Publish pre-release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REPOSITORY_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    name: Publish OpenAPI Diff Action pre-release packages to Github
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup nbgv
        uses: dotnet/nbgv@master
      - name: Create the package
        run: dotnet pack --configuration Release --output ./nupkgs /p:PublicRelease=true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs
          path: ./nupkgs
      - name: Publish packages
        run: dotnet nuget push '*.nupkg' --source ${{ env.REPOSITORY_URL }} --api-key ${{ secrets.NUGET_AUTH_TOKEN_LIB }} --skip-duplicate --no-symbols true
        working-directory: ./nupkgs
